= Text Encoding

A presentation on text encoding that reviews basic computer memory concepts and
covers ASCII and Unicode.

== Pre-Built Slides

See `Releases` > `Latest Development Build` > `assets` > `index.pdf` for the
latest build.

== Building the Slides

Requirements for main document (if not using Docker):

* Python 3.6+
** Alternatively, a TeX installation (see link:packages.txt[`packages.txt`] for
   list of extra required packages)
* R 4.0+
* C++17 compiler (GCC/Clang/etc.)

=== Unix

To build on Unix/Linux/macOS without a TeX installation:

[source,shell]
----
./install.py install
. local/activate
latexmk                       # or: make index
                              # build should be at target/index.pdf

deactivate                    # when leaving the project directory
----

With a TeX installation:

[source,shell]
----
Rscript -e "renv::hydrate()"
tlmgr install $(cat packages) # if missing any required packages
latexmk                       # or: make index
----

=== Windows

To build on Windows without a TeX installation (not tested):

[source,powershell]
----
python3 install.py install
. local/activate.ps1
latexmk                       # or: make index
                              # build should be at target/index.pdf

deactivate                    # when leaving the project directory
----

With a TeX installation:

[source,shell]
----
Rscript -e "renv::hydrate()"
# install any missing packages specified in packages.txt
latexmk                       # or: make index
----

=== Docker

To build with Docker:

[source,shell]
----
DOCKER_BUILDKIT=1 docker build --output target .  # build should be at target/index.pdf
----

== Building Listings

=== ASCII Decoder

Requirements:

* GNU Make (or check steps in Makefile)
* Rust compiler (`rustc`)

[source,shell]
----
make ascii-decoder
----

=== UTF-8 Decoder

Requirements:

* GNU Make (or check steps in Makefile)
* C++17 compiler (GCC/Clang/etc.)

[source,shell]
----
CC=<...> make utf8-decoder
----

== License

This project is licensed under the MIT license. See link:LICENSE.txt[LICENSE.txt] for
more details.
